### ISSUE TITLE
No publications found by an author and not finding a file

### ISSUE THREAD

**Issue by rhuanzgoda** [robsonsmartins/php-projects#16]
Hello. the tool is not finding the user "cativa-medium" in Issuu.

and i've tried to download this file: "https://issuu.com/cativa-medium/docs/fidodido_catalogopv2017_issuu" it appears to me that the publication wasnt found.
The same happens with all files from this user.

**Comment by rhuanzgoda** [comment]
Ajuda amigo!! queria muito poder utilizar a ferramenta!! rsrssr

**Comment by robsonsmartins** [comment]
Hello,
This problem is in Issuu metadata! Is very strange! 

1. The search result for this publication: "[https://search.issuu.com/api/2_0/document?q=*&responseParams=*&explicit=1&documentId=170621114204-654ceb3606359d58c94765a99fb15e5c](https://search.issuu.com/api/2_0/document?q=*&responseParams=*&explicit=1&documentId=170621114204-654ceb3606359d58c94765a99fb15e5c)" is empty.

2. In author page: "[https://issuu.com/cativa-medium](https://issuu.com/cativa-medium)", no publications is in view.

I correct now the download routine for a single publication, bypassing data from search query result (if it's empty), and getting the data from a script snippet within publication home page (html).

"Download all publications from author" no supports this workaround.

Best regards,
Robson Martins

**Comment by rhuanzgoda** [comment]
Good Morning.

Not working yet.

all these files show me the same msgbox. in the single publication routine.

![qqqq](https://user-images.githubusercontent.com/29925859/28460380-2fb45e92-6de8-11e7-8a90-900c70e3256c.JPG)

https://issuu.com/cativa-medium/docs/cativa_pv17_catalogo_p__gina_indivi
http://issuu.com/cativa-medium/docs/habana_pv17_issuu_
https://issuu.com/cativa-medium/docs/fidodido_catalogopv2017_issuu
https://issuu.com/cativa-medium/docs/cativa_kids_pv17__issuu_
https://issuu.com/cativa-medium/docs/cativa_pv17_-__issu_

**Comment by rhuanzgoda** [comment]
Im using Today (31/07) and it is working perfectly. Thank you very much!!

**Comment by robsonsmartins** [comment]
Thank you for your reporting.
Best regards,
Robson Martins
